add safe classes
isaacs/node-primordials pull request #9
Opened 2023-07-06 10:36 UTC by MoLow

2023-07-11 19:50 UTC, isaacs requested changes
Looks mostly fine, but tests aren't complete yet.

```
----------|---------|----------|---------|---------|-----------------------------------------------------------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                     
----------|---------|----------|---------|---------|-----------------------------------------------------------------------
All files |   99.09 |      100 |    82.5 |   99.09 |                                                                       
 index.ts |   99.09 |      100 |    82.5 |   99.09 | 2381-2394,2439-2440,2470-2471,2486-2487,2495-2496,2503-2504,2512-2518 
----------|---------|----------|---------|---------|-----------------------------------------------------------------------
```

2023-07-11 19:50 UTC, isaacs commented on src/index.ts
> +          next ??= uncurryThis(createIterator(dummy).next)
Not supported on node 14, so this is a breaking change. It's a function, so `||=` is equivalent.
```suggestion
          next ||= uncurryThis(createIterator(dummy).next)
```

2023-07-11 20:40 UTC, MoLow commented
@isaacs can we remove node 14 from CI? it is EOL

2023-07-26 18:30 UTC, isaacs commented on src/index.ts
> +interface Constractable<T> extends NewableFunction {
`s/Constractable/Constructable/`?

2023-09-15 19:59 UTC, closed without merging